---
- hosts: linux_nodes
  become: yes
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Install MySQL/MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Install PHP
      apt:
        name: php libapache2-mod-php php-mysql
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes
