---
- hosts: windows_nodes
  tasks:
    - name: Install Nginx
      win_chocolatey:
        name: nginx
        state: present

    - name: Install MySQL
      win_chocolatey:
        name: mysql
        state: present

    - name: Install PHP
      win_chocolatey:
        name: php
        state: present

    - name: Ensure Nginx is running
      win_service:
        name: nginx
        start_mode: auto
        state: started
